config/routes.rb
Hello::Application.routes.draw do
  resources :users

  get "welcome/index"
  resources :phonebooks

  root 'welcome#index'

end

app/models/phonebook.rb
class Phonebook < ActiveRecord::Base
  validates_uniqueness_of :phoneno , :message => " already exist"
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/phonebooks_controller.rb
class PhonebooksController < ApplicationController
  before_action :set_phonebook, only: [:show, :edit, :update, :destroy]

  # GET /phonebooks
  # GET /phonebooks.json
  def index
    @phonebooks = Phonebook.all
  end

  # GET /phonebooks/1
  # GET /phonebooks/1.json
  def show
  end

  # GET /phonebooks/new
  def new
    @phonebook = Phonebook.new
  end

  # GET /phonebooks/1/edit
  def edit
  end

  # POST /phonebooks
  # POST /phonebooks.json
  def create
    @phonebook = Phonebook.new(phonebook_params)

    respond_to do |format|
      if @phonebook.save
        format.html { redirect_to @phonebook, notice: 'Phonebook was successfully created.' }
        format.json { render action: 'show', status: :created, location: @phonebook }
      else
        format.html { render action: 'new' }
        format.json { render json: @phonebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phonebooks/1
  # PATCH/PUT /phonebooks/1.json
  def update
    respond_to do |format|
      if @phonebook.update(phonebook_params)
        format.html { redirect_to @phonebook, notice: 'Phonebook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @phonebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phonebooks/1
  # DELETE /phonebooks/1.json
  def destroy
    @phonebook.destroy
    respond_to do |format|
      format.html { redirect_to phonebooks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phonebook
      @phonebook = Phonebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phonebook_params
      params.require(:phonebook).permit(:fullname, :phoneno, :address, :email)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :security_question, :answer)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/phonebooks_helper.rb
module PhonebooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hello</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Hello header</h1>
<%= link_to "Phonebook" ,  phonebooks_path %>
<%= yield %>

</body>
</html>

app/views/phonebooks/_form.html.erb
<%= form_for(@phonebook) do |f| %>
  <% if @phonebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@phonebook.errors.count, "error") %> prohibited this phonebook from being saved:</h2>

      <ul>
      <% @phonebook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %><br>
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :phoneno %><br>
    <%= f.text_field :phoneno %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/phonebooks/edit.html.erb
<h1>Editing phonebook</h1>

<%= render 'form' %>

<%= link_to 'Show', @phonebook %> |
<%= link_to 'Back', phonebooks_path %>

app/views/phonebooks/index.html.erb
<%= link_to "back" , _back_url %>
<h1>Listing phonebooks</h1>
<table>
  <thead>
    <tr>
      <th>Fullname</th>
      <th>Phoneno</th>
      <th>Address</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @phonebooks.each do |phonebook| %>
      <tr>
        <td><%= phonebook.fullname %></td>
        <td><%= phonebook.phoneno %></td>
        <td><%= phonebook.address %></td>
        <td><%= phonebook.email %></td>
        <td><%= link_to 'Show', phonebook %></td>
        <td><%= link_to 'Edit', edit_phonebook_path(phonebook) %></td>
        <td><%= link_to 'Destroy', phonebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phonebook', new_phonebook_path %>

app/views/phonebooks/new.html.erb
<h1>New phonebook</h1>

<%= render 'form' %>

<%= link_to 'Back', phonebooks_path %>

app/views/phonebooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fullname:</strong>
  <%= @phonebook.fullname %>
</p>

<p>
  <strong>Phoneno:</strong>
  <%= @phonebook.phoneno %>
</p>

<p>
  <strong>Address:</strong>
  <%= @phonebook.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @phonebook.email %>
</p>

<%= link_to 'Edit', edit_phonebook_path(@phonebook) %> |
<%= link_to 'Back', phonebooks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :security_question %><br>
    <%= f.text_field :security_question %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Security question</th>
      <th>Answer</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.security_question %></td>
        <td><%= user.answer %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Security question:</strong>
  <%= @user.security_question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @user.answer %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
Hello this is my home page.